const AnimalList={0:[
	["Dog",require("../assets/dog.png")],
	["Cat",require("../assets/cat.png")],
	["Dog",require("../assets/dog.png")],
	["Cat",require("../assets/cat.png")],
	["Dog",require("../assets/dog.png")],
	["Cat",require("../assets/cat.png")],
	["Dog",require("../assets/dog.png")],
	["Cat",require("../assets/cat.png")],
	["Dog",require("../assets/dog.png")],
	["Cat",require("../assets/cat.png")],
	["Dog",require("../assets/dog.png")],
	["Cat",require("../assets/cat.png")],
	["Dog",require("../assets/dog.png")],
	["Cat",require("../assets/cat.png")],
	["Dog",require("../assets/dog.png")],
	["Cat",require("../assets/cat.png")],
	["Dog",require("../assets/dog.png")],
	["Cat",require("../assets/cat.png")],
	["Dog",require("../assets/dog.png")],
	["Cat",require("../assets/cat.png")],
],
};
export default AnimalList;