const DashboardConstant={0:
	[
		["Birds",require("../assets/bird.png")],
		["Animals",require("../assets/animal.png")],

	],
1:[
	["पक्षियों",require("../assets/bird.png")],
	["जानवर",require("../assets/animal.png")],
],
2:[
	["পাখি",require("../assets/bird.png")],
	["প্রাণী",require("../assets/animal.png")],
],
3:[
	["પક્ષીઓ",require("../assets/bird.png")],
	["પ્રાણી",require("../assets/animal.png")],
],
4:[
	["ಪಕ್ಷಿಗಳು",require("../assets/bird.png")],
	["ಪ್ರಾಣಿ",require("../assets/animal.png")],
],
5:[
	["പക്ഷികൾ",require("../assets/bird.png")],
	["മൃഗം",require("../assets/animal.png")],
],
6:[
	["पक्षी",require("../assets/bird.png")],
	["प्राणी",require("../assets/animal.png")],
],
7:[
	["चराहरू",require("../assets/bird.png")],
	["जनावर",require("../assets/animal.png")],
],
8:[
	["ପକ୍ଷୀଗଣ",require("../assets/bird.png")],
	["ପଶୁ",require("../assets/animal.png")],
],
9:[
	["ਪੰਛੀ",require("../assets/bird.png")],
	["ਜਾਨਵਰ",require("../assets/animal.png")],
],
10:[
	["پکي",require("../assets/bird.png")],
	["حيوان",require("../assets/animal.png")],
],
11:[
	["பறவைகள்",require("../assets/bird.png")],
	["விலங்கு",require("../assets/animal.png")],
],
12:[
	["పక్షులు",require("../assets/bird.png")],
	["జంతువు",require("../assets/animal.png")],
],
13:[
	["پرندے",require("../assets/bird.png")],
	["جانور",require("../assets/animal.png")],
],
};
export default DashboardConstant;