const Statelist={0:[
	["Andhra Pradesh",require("../assets/AndhraPradesh.png")],
	["Arunachal Pradesh",require("../assets/ArunachalPradesh.png")],
	["Assam",require("../assets/Assam.png")],
	["Bihar",require("../assets/Bihar.png")],
	["Chandigarh",require("../assets/chandigarh.png")],
	["Chhattisgarh",require("../assets/Chattisgarh.png")],
	["Goa",require("../assets/Goa.png")],
	["Gujrat",require("../assets/Gujrat.png")],
	["Haryana",require("../assets/Haryana.png")],
	["Himachal Pradesh",require("../assets/HimachalPradesh.png")],
	["Jharkhand",require("../assets/Jharkhand.png")],
	["Karnataka",require("../assets/Karnataka.png")],
	["Kerala",require("../assets/Kerela.png")],
	["Ladakh",require("../assets/Ladakh.png")],
	["Madhya Pradesh",require("../assets/MadhyaPradesh.png")],
	["Maharashtra",require("../assets/Maharastra.png")],
	["Manipur",require("../assets/Manipur.png")],
	["Meghalaya",require("../assets/Meghalaya.png")],
	["Mizoram",require("../assets/Mizoram.png")],
	["Nagaland",require("../assets/Nagaland.png")],
	["Odisha",require("../assets/odisha.png")],
	["Punjab",require("../assets/Punjab.png")],
	["Rajasthan",require("../assets/Rajasthan.png")],
	["Sikkim",require("../assets/Sikkim.png")],
	["Tamil Nadu",require("../assets/TamilNadu.png")],
	["Telangana",require("../assets/telangana.png")],
	["Tripura",require("../assets/Tripura.png")],
	["Uttrakhand",require("../assets/Uttrakhand.png")],
	["Uttar Pradesh",require("../assets/UttarPradesh.png")],
	["West Bengal",require("../assets/WestBengal.png")],
],
1:[
	["कुत्ता",require("../assets/dog.png")],
	["बिल्ली",require("../assets/cat.png")],
],
2:[
	["কুকুর",require("../assets/dog.png")],
	["বিড়াল",require("../assets/cat.png")],
],
3:[
	["કૂતરો",require("../assets/dog.png")],
	["બિલાડી",require("../assets/cat.png")],
],
4:[
	["ನಾಯಿ",require("../assets/dog.png")],
	["ಬೆಕ್ಕು",require("../assets/cat.png")],
],
5:[
	["നായ",require("../assets/dog.png")],
	["പൂച്ച",require("../assets/cat.png")],
],
6:[
	["कुत्रा",require("../assets/dog.png")],
	["मांजर",require("../assets/cat.png")],
],
7:[
	["कुकुर",require("../assets/dog.png")],
	["बिरालो",require("../assets/cat.png")],
],
8:[
	["କୁକୁର",require("../assets/dog.png")],
	["ବିଲେଇ",require("../assets/cat.png")],
],
9:[
	["ਕੁੱਤਾ",require("../assets/dog.png")],
	["ਬਿੱਲੀ",require("../assets/cat.png")],
],
10:[
	["ڪتو",require("../assets/dog.png")],
	["ٻلي",require("../assets/cat.png")],
],
11:[
	["நாய்",require("../assets/dog.png")],
	["பூனை",require("../assets/cat.png")],
],
12:[
	["కుక్క",require("../assets/dog.png")],
	["పిల్లి",require("../assets/cat.png")],
],
13:[
	["کتا",require("../assets/dog.png")],
	["کیٹ",require("../assets/cat.png")],
],
};
export default Statelist;