const TapAndLearn={
	0:{
		0:["Listen and tap on the image of bird's voice",
			require("../assets/koyal.mp3"),
			require("../assets/penguin.png"),
			require("../assets/Cuckoo.png"),
			require("../assets/peacock.png"),
			require("../assets/crow.png"),
			require("../assets/owl.png"),
			"Play Audio",
			"2",
			"Yay ! you got that right",
			"Better Luck Next Time",
			"Next",
			"Retry",
			"Prev",
			"You have selected Penguin",
			"You have selected Cuckoo",
			"You have selected Peacock",
			"You have selected Crow",
			"You have selected Owl",
		],
		1:["Listen and tap on the image of bird's voice",
			require("../assets/crow.mp3"),
			require("../assets/crow.png"),
			require("../assets/Cuckoo.png"),
			require("../assets/penguin.png"),
			require("../assets/owl.png"),
			require("../assets/peacock.png"),
			"Play Audio",
			"1",
			"Yay ! you got that right",
			"Better Luck Next Time",
			"Next",
			"Retry",
			"Prev",
			"You have selected Crow",
			"You have selected Cuckoo",
			"You have selected Penguin",
			"You have selected Owl",
			"You have selected Peacock",
		],
	},
	1:{
		0:["पक्षी की आवाज की छवि को सुनें और टैप करें",
			require("../assets/koyal.mp3"),
			require("../assets/penguin.png"),
			require("../assets/Cuckoo.png"),
			require("../assets/peacock.png"),
			require("../assets/crow.png"),
			require("../assets/owl.png"),
		]}
};
export default TapAndLearn;